src/buysell2game/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "pages#home"
  get "/restricted", to: "pages#restricted"
  get "listings", to: "listings#index", as: "listings"
  get "listings/category/:id", to: "listings#index", as: "listings_category"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "delete_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "orders", to: "orders#index", as: "orders"
  post "orders", to: "orders#create"
  get "orders/new", to: "orders#new", as: "new_order"
  get "orders/:id", to: "orders#show", as: "order"
  post "items", to: "items#create"
  get "items/new", to: "items#new", as: "new_item"
  delete "items/:id", to: "items#destroy", as: "delete_item"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "payments/webhook", to: "payments#webhook"
  post "payments", to: "payments#create_checkout_session", as: "create_checkout_session"
  get "favourites", to: "favourites#index", as: "favourites"
  post "favourites", to: "favourites#create"
  delete "favourites", to: "favourites#destroy"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/buysell2game/app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category

  enum condition: { brand_new_mint: 1, like_new: 2, great: 3, good: 4, fair: 5 }
  enum listing_status: { draft: 1, listed: 2, sold: 3, archived: 4 }
  enum shipping: { post_only: 1, pick_up_only: 2, aus_post_or_pick_up: 3 }

  has_one_attached :picture

  # has_many_attached :picture
  has_one :item

  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourite
  before_validation :convert_price_to_cents, if: :price_changed?

  # Data validations, even the form include :require => true, this create an extra layer to ensure data received is valid
  validates :listing_name, :condition, :price, :description, :category_id, :shipping, presence: true
  validates :listing_name, length: { minimum: 2 }
  
  # Data sanitsations
  before_save :remove_whitespace
  before_save :censor_profanities

  private 
  
  def remove_whitespace 
    self.listing_name = self.listing_name.strip
    self.description = self.description.strip
  end

  def censor_profanities

    profanities = ["shit", "fuck", "cunt", "sex"]

    def replace_word(bad_word)
      letters = bad_word.split("")
      word_length = letters.length
      sub_chars = ["!", "@", "#", "$", "%", "^", "&", "*"]
      numbers_of_sub_chars = word_length - 2
      sub_word = []
      numbers_of_sub_chars.times { sub_word << sub_chars.sample }
      sub_word.unshift(letters[0])
      sub_word.append(letters[-1])
      @text = sub_word.join
    end

    name_array = self.listing_name.split(" ")
    profanities.each do |prof|
      word = prof.downcase
      replace_word(word)
      self.listing_name = self.listing_name.gsub(word, @text)
      self.description = self.description.gsub(word, @text)
    end

  end
  
  def convert_price_to_cents 
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end 
  
end

src/buysell2game/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  # Below before action ensure unauthorised user cannot use URL to temper with the listing
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :set_form_vars, only: [:new, :edit]

  def index

    # Filter the listings by category_id and user_id for shop by "Category" and "My listings" features.
    # This is possible because of the Foreign keys user_id and category_id attributes in the Listings table
    # The params[:id] (with the listing category names) is passed in from the link tags eg. "listings_category_path("puzzles")" in the view home.html.erb page and navbar.
    # Only listed listings are showed to users. Users wont see their own listing in buying page.
    # For those listing that have listing_status others than "listed" such as "draft", "sold" or "archived", only their owners can see those in their "my listings" page.

    if !user_signed_in?
      case params[:id]
      when "all"
        @listings = Listing.all.where(listing_status: "listed")
      when "family"
        @listings = Listing.where(category_id: 1, listing_status: "listed")
      when "strategy"
        @listings = Listing.where(category_id: 2, listing_status: "listed")
      when "classic"
        @listings = Listing.where(category_id: 3, listing_status: "listed")
      when "puzzles"
        @listings = Listing.where(category_id: 4, listing_status: "listed")
      when "fantasy"
        @listings = Listing.where(category_id: 5, listing_status: "listed")
      when "others"
        @listings = Listing.where(category_id: 6, listing_status: "listed")
      else
        render :file => "#{Rails.root}/public/404.html", layout: false, status: :not_found
      end
    else
      case params[:id]
      when "all"
        @listings = Listing.all.where(listing_status: "listed").where.not(user_id: current_user.id)
      when "family"
        @listings = Listing.where(category_id: 1, listing_status: "listed").where.not(user_id: current_user.id)
      when "strategy"
        @listings = Listing.where(category_id: 2, listing_status: "listed").where.not(user_id: current_user.id)
      when "classic"
        @listings = Listing.where(category_id: 3, listing_status: "listed").where.not(user_id: current_user.id)
      when "puzzles"
        @listings = Listing.where(category_id: 4, listing_status: "listed").where.not(user_id: current_user.id)
      when "fantasy"
        @listings = Listing.where(category_id: 5, listing_status: "listed").where.not(user_id: current_user.id)
      when "others"
        @listings = Listing.where(category_id: 6, listing_status: "listed").where.not(user_id: current_user.id)
      when "#{current_user.id}"
        @listings = current_user.listings
      when "favourites"
        user_favouties = User.find_by(id: current_user.id).favourites
        @listings = []
        user_favouties.each do |fav|
          @listings << fav.listing
        end
      else
        render :file => "#{Rails.root}/public/404.html", layout: false, status: :not_found
      end
    end
  end

  def show

    # Users can only view listed listings. If a listing is not at "listed" status, only the owner of the listing can view it
    if @listing.listing_status != "listed"
      if current_user.id != Listing.find(params[:id]).user_id
        flash[:alert] = "Unauthorised access"
        redirect_to root_path
      end
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)

    update_listing_status

    if @listing.save
      redirect_to @listing, notice: "Listing successfully created"
    else
      set_form_vars
      render "new", notice: "An error has occurred, please try again"
    end
  end

  def edit
    #Only listing with status "draft" or "listed" can be edited
    if @listing.listing_status == "archived"
      flash[:alert] = "This listing details can no longer be changed"
    end

  end

  def update
    
    @listing.update(listing_params)
    
    update_listing_status

    if @listing.save
      redirect_to @listing, notice: "Listing successfully updated!"
    else
      set_form_vars
      render "edit", notice: "An error has occurred, please try again"
    end
  end

  def destroy
    if @listing.listing_status == "sold" || @listing.listing_status == "archived"
      flash[:alert] = "This listing can no longer be deleted as it has been sold or archived"
    else
      @listing.destroy
      redirect_to listings_category_path("#{@listing.user_id}"), notice: "Listing succesfully deleted"
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:listing_name, :price, :category_id, :condition, :description, :picture, :shipping)
  end

  #change listing status once the form is submitted
  def update_listing_status
    case params[:listing_status]
    when "Create Listing", "Update Listing"
      @listing.update(listing_status: 2)
    when "Save as draft"
      @listing.update(listing_status: 1)
    when "Attach receipt"
      @listing.update(listing_status: 4)
    end
  end

  def authorize_user
    if @listing.user_id != current_user.id
      flash[:alert] = "Unauthorised access"
      redirect_to root_path
    end
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def set_form_vars
    @categories = Category.all
    @conditions = Listing.conditions.keys
    @shipping_methods = Listing.shippings.keys
  end
end

src/buysell2game/app/helpers/listings_helper.rb
module ListingsHelper
  def format_text(string)
    arr = string.split("_").map do |word|
      word.capitalize
    end
    arr.join(" ")
  end

  def format_category(category)
    category.capitalize
  end

  def format_price(price)
    "$#{price/ 100.0}"
  end 
end

src/buysell2game/app/views/listings/_form.html.erb
<%= form_with model: @listing, local: true do |f| %>
  <div class='form-group mb-3'>
    <%= f.label :listing_name, class: "form-label" %>
    <%= f.text_field :listing_name, :required => true %>
  </div>
  <div class='form-group mb-3'>
    <%= f.label :price, class: "form-label" %>
    <%= f.number_field :price, step:"0.01", :required => true %>
  </div>
  <div class='form-group mb-3'>
    <%= f.label :category_id, class: "form-label" %>
    <%= f.select :category_id, @categories.map {|c| [c.name.capitalize, c.id]}, :required => true, class: "form-select" %>
  </div>
  <h5 class="mb-3">Condition</h5>
  <%@conditions.each do |option| %>
    <%= f.radio_button :condition, option, :required => true, class:"mr-2" %>
    <%= f.label :condition, format_text(option), class: "form-label mr-1" %>
  <% end %>
  <h5 class="mb-3">Shipping method available</h5>
  <%@shipping_methods.each do |method| %>
    <%= f.radio_button :shipping, method, :required => true, class:"mr-2" %>
    <%= f.label :shipping, format_text(method), class: "form-label mr-1" %>
  <% end %>
  <div class='form-group mb-3'>
    <%= f.label :picture, class: "form-label" %>
    <%= f.file_field :picture, accept: "image/png,image/jpg,image/jpeg", class: "form-select" %>
  </div>
  <div class='form-group mb-3'>
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, :required => true, class: "form-control" %>
  </div>
  <div class='actions'>
    <%= f.submit :name => "listing_status" %>
    <%= f.submit "Save as draft", :name => "listing_status" %>
  </div>
<% end %>

src/buysell2game/app/views/listings/_receipt.html.erb
<%= form_with model: @listing, local: true do |f| %>
  <div class='form-group mb-3'>
    <%= f.label :picture, class: "form-label" %>
    <%= f.file_field :picture, accept: "image/png,image/jpg,image/jpeg", class: "form-select" %>
  </div>
  <div class='actions'>
    <%= f.submit "Attach receipt", :name => "listing_status" %>
  </div>
<% end %>

src/buysell2game/app/views/listings/edit.html.erb
<% if @listing.listing_status != "sold" && @listing.listing_status != "archived" %>
  <h1> Edit listing - <%= @listing.listing_name %></h1>
  <p>*Kindly note, by clicking <strong>"Update Listing"</strong> button, your listing will be <strong>updated</strong> and <strong>listed</strong></p>
  <p>*If you have not listed your item and only want to update the draft, please click <strong>"Save as draft"</strong></p>
  <%= render "form" %>

  <%# Render update receipt form when listing status is "sold" %>
<% elsif @listing.listing_status == "sold" %>
  <h1> Update shipping receipt - listing - <%= @listing.listing_name %></h1>
  <%= render "receipt" %>
<% end %>

src/buysell2game/app/views/listings/index.html.erb
<div>
  <% if user_signed_in? && params[:id] == "#{current_user.id}" %>
    <h3 class="display-4 text-center">Your listed board games</h3>
  <% else%>
    <h3 class="display-4 text-center"><%= "#{params[:id]}".capitalize + " Board Games" %></h3>
  <% end %>
</div>

<section class="container d-flex justify-content-center">

  <div class="d-flex flex-wrap justify-content-center">

    <% if !@listings.empty? %>
      <%# Create ecommerce cards for each listing in the category (filtered by the controller method index) %>
      <% @listings.each do |listing| %>
        <div class="d-flex m-4">
          <div class="card" style="width: 18rem;">
            <div class="card-img top">
              <% if listing.picture.attached? %>
                <%= image_tag listing.picture, alt: listing.listing_name, class:"card-img top" %>
              <% else %>
                <%= image_tag "hero-image.jpg", alt: "dungeon and dragon board game", class:"thumbnail card-img top" %>
              <% end %>
            </div>
            <div class="card-body d-flex flex-column justify-content-between">
              <h4 class="card-title flex-grow-1 me-3" style="height: 58px"><%= listing.listing_name %></h4>
              <div class="d-flex justify-content-between mb-3">
                <h5><%= format_price(listing.price) %></h5>
                <% if params[:id] == "favourites" %>
                  <%= button_to "remove from fav", { :controller => "favourites", :action => "destroy" }, { :method => :delete, :params => { :listing_id => listing.id}, class: "btn-light btn-sm"} %>
                <% else %>
                  <%= button_to "add to fav", { :controller => "favourites", :action => "create" }, { :method => :post, :params => { :listing_id => listing.id}, class: "btn-light btn-sm"} %>
                <% end %>
              </div>
              <% if user_signed_in? && current_user.id == listing.user_id %>
                <h5>Listing status: <%= listing.listing_status.capitalize %></h5>
                <div class="d-flex justify-content-between align-items-end mt-3">
                  <% if listing.listing_status != "sold" && listing.listing_status != "archived" %>
                    <%= link_to "Edit", edit_listing_path(listing.id), class: "btn btn-primary" %>
                  <% end %>
                  <%= link_to "View", listing_path(listing.id), class: "btn btn-primary" %>
                </div>
                <% if listing.listing_status == "sold" %>
                  <hr>
                  <div class="d-flex">
                    <%= link_to "Attach shipping receipt", edit_listing_path(listing.id), class: "btn btn-primary" %>
                  </div>
                <% end %>
              <% else %>
                <div class="d-flex justify-content-between align-items-end">
                  <%= button_to "Add to cart", { :controller => "orders", :action => "create" }, { :method => :post, :params => { :listing_id => listing.id}, class: "btn btn-primary"} %>
                  <%= link_to "More details", listing_path(listing.id), class: "card-link" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
  </div>

    <% else %>
      <div>
      <h4> The list you're trying to access is empty </h4>
      </div>
    <% end %>

</section>

src/buysell2game/app/views/listings/new.html.erb
<h1> Create Listing </h1>
<%= render "form" %>

src/buysell2game/app/views/listings/show.html.erb
<section class="containter">
  <div class="jumbotron m-4 mb-4">
    <div class="row pr-2">
      <div class="col-md-6">
        <% if !@listing.picture.attached? %>
          <%= image_tag "hero-image.jpg", alt: "dungeon and dragon board game", class:"img-fluid" %>
        <% else %>
          <%= image_tag @listing.picture, alt: @listing.listing_name, class:"img-fluid" %>
        <% end %>
      </div>
      <div class="col-md-6 d-flex flex-column mt-4">
        <h1 class="mb-sm-2 mb-md-5"><%= @listing.listing_name %></h1>
        <h3 class=" d-flex">Price: <%= format_price(@listing.price) %></h3>
        <h5 class="text-muted">Description:</h5>
        <p><%= @listing.description %></p>
        <h5 class="d-flex text-muted">Condition: <%= format_text(@listing.condition) %></h5>
        <h5 class="d-flex text-muted">Shipping method: <%= format_text(@listing.shipping) %></h5>
        <% if current_user && current_user.id == @listing.user_id %>
          <h5>Listing status: 
            <span><strong><%= @listing.listing_status.capitalize %></strong></span></h5>
          <div class="d-flex">
            <% if @listing.listing_status != "sold" && @listing.listing_status != "archived" %>
              <%= link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-primary me-3" %>
              <%= link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
            <% end %>
          </div>
          <div class="d-flex">
            <% if @listing.listing_status == "sold" %>
              <%= link_to "Attach shipping receipt", edit_listing_path(@listing.id), class: "btn btn-primary mt-3" %>
            <% end %>
          </div>
        <% else %>
          <div>
            <%= button_to "Add to cart", { :controller => "orders", :action => "create" }, { :method => :post, :params => { :listing_id => @listing.id}, class: "btn btn-primary mt-4"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>