src/buysell2game/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "pages#home"
  get "/restricted", to: "pages#restricted"
  get "listings", to: "listings#index", as: "listings"
  get "listings/category/:id", to: "listings#index", as: "listings_category"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "delete_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "orders", to: "orders#index", as: "orders"
  post "orders", to: "orders#create"
  get "orders/new", to: "orders#new", as: "new_order"
  get "orders/:id", to: "orders#show", as: "order"
  post "items", to: "items#create"
  get "items/new", to: "items#new", as: "new_item"
  delete "items/:id", to: "items#destroy", as: "delete_item"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "payments/webhook", to: "payments#webhook"
  post "payments", to: "payments#create_checkout_session", as: "create_checkout_session"
  get "favourites", to: "favourites#index", as: "favourites"
  post "favourites", to: "favourites#create"
  delete "favourites", to: "favourites#destroy"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/buysell2game/app/views/shared/_footer.html.erb
<section class="footer">
  <nav class="footer-nav">
    <div class="footer-links">
      <a class="nav-link disabled" href="#">Home</a>
    </div>
    <div class="footer-links">
      <a class="nav-link disabled" href="#">About us</a>
    </div>
    <div class="footer-links">
      <a class="nav-link disabled" href="#">Contact</a>
    </div>
    <div class="footer-links">
      <a class="nav-link disabled" href="#">Privacy</a>
    </div>
    <div class="footer-links">
      <a class="nav-link disabled" href="#">Terms of service</a>
    </div>
  </nav>
  <p>
    &copy; KBS2022
  </p>
</section>

src/buysell2game/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= image_tag "logo.jpg", alt: "a octahedron shape dice logo", class: "logo-image" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Top seller</a>        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Community</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><%= link_to "Classic", listings_category_path("classic"), class: "dropdown-item" %></li>
            <li><%= link_to "Family", listings_category_path("family"), class: "dropdown-item" %></li>
            <li><%= link_to "Strategy", listings_category_path("strategy"), class: "dropdown-item" %></li>
            <li><%= link_to "Fantasy", listings_category_path("fantasy"), class: "dropdown-item" %></li>
            <li><%= link_to "Puzzles", listings_category_path("puzzles"), class: "dropdown-item" %></li>
            <li><%= link_to "Others", listings_category_path("others"), class: "dropdown-item" %></li>
            <div class="dropdown-divider"></div>
            <li><%= link_to "Shop all", listings_category_path("all"), class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
    <div>
      <ul class="nav justify-content-end">
        <li class="nav-item active">
          <%#Only show user dropdown menu option when the user is signed in %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= image_tag "user.jpg", alt: "a human shape", class: "nav-icon-image" %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><%= link_to "Create listing", new_listing_path, class: "dropdown-item" %></li>
                  <li><%= link_to "My listings", listings_category_path("#{current_user.id}"), class: "dropdown-item" %></li>
                  <li><%= link_to "My orders", orders_path, class: "dropdown-item" %></li>
                  <li><%= link_to "My favourites", favourites_path, class: "dropdown-item" %></li>
                  <div class="dropdown-divider"></div>
                  <li><a class="dropdown-item nav-link disabled" href="#">Account Settings</a></li>
                </ul>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="/favourites"><%= image_tag "fav.jpg", alt: "a heart shape", class: "nav-icon-image" %></a>
          </li>
        </li>
        <a class="nav-link" href="/orders/show"><%= image_tag "cart.jpg", alt: "shopping cart", class: "nav-icon-image" %></a>
      </li>
    </li>
  </ul>
</div>
</div>
</nav>