src/buysell2game/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "pages#home"
  get "/restricted", to: "pages#restricted"
  get "listings", to: "listings#index", as: "listings"
  get "listings/category/:id", to: "listings#index", as: "listings_category"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "delete_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "orders", to: "orders#index", as: "orders"
  post "orders", to: "orders#create"
  get "orders/new", to: "orders#new", as: "new_order"
  get "orders/:id", to: "orders#show", as: "order"
  post "items", to: "items#create"
  get "items/new", to: "items#new", as: "new_item"
  delete "items/:id", to: "items#destroy", as: "delete_item"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "payments/webhook", to: "payments#webhook"
  post "payments", to: "payments#create_checkout_session", as: "create_checkout_session"
  get "favourites", to: "favourites#index", as: "favourites"
  post "favourites", to: "favourites#create"
  delete "favourites", to: "favourites#destroy"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/buysell2game/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items

  enum order_status: { pending: 1, paid_await_shipping: 2, shipped: 3, archived: 4 }
  has_one :payment
end

src/buysell2game/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user
  before_action :set_order, only: [:index, :show, :create]

  def index
    if current_user.orders.empty?
      flash[:alert] = "You have no order yet!"
      redirect_back(fallback_location: root_path)
    else
      @orders = current_user.orders.where.not(order_status: "pending")
    end
  end

  def show
    if !@order || @order.items.empty?
      flash[:notice] = "Your cart is empty!"
      redirect_to root_path
    else
      # Eager load listing details as those details will be used to display listing line items in the Order page.
      @items = @order.items.all.eager_load(:listing)
    end
  end

  def new
    @order = Order.new
  end

  def create
    listing = Listing.find_by(id: params[:listing_id])
    # Only create a new line in Orders table if there isnt already one pending.
    if !@order
      @order = Order.create(user_id: current_user.id)
      @order_total_before_checkout = 0
    end
    #If the item is not already in the list of items under the order. create one
    #Add the item price to the order total (before checkout) and update it
    if !@order.items.find_by(listing_id: listing.id)
      item = @order.items.create(listing_id: listing.id, price: listing.price)
      flash[:notice] = "Item succesfully added."
      @order_total_before_checkout += item.price
      @order.update(total: @order_total_before_checkout)

      redirect_back(fallback_location: root_path)
      #If already in the order, flash message and do not add
    else
      flash[:alert] = "Item already added."
      redirect_back(fallback_location: root_path)
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
  end

  private

  def set_order
    @order = current_user.orders.find_by(order_status: "pending")
    #Record the order total before checkout
    if @order
      items = @order.items.all
      @order_total_before_checkout = 0
      items.each do |item|
        @order_total_before_checkout += item.price
      end
    end
  end

  def authorize_user
    order = Order.find_by(id: params[:id])
    if order && order.user_id != current_user.id
      flash[:alert] = "Unauthorised access"
      redirect_to root_path
    end
  end
end

src/buysell2game/app/helpers/orders_helper.rb
module OrdersHelper
end

src/buysell2game/app/views/orders/index.html.erb
<h2>Order history</h2>
<section>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Order number</th>
        <th scope="col">Order status</th>
        <th scope="col">Total</th>
        <th scope="col">Updated at</th>
        <th scope="col">Payment receipt</th>
      </tr>
    </thead>
    <tbody>
      <%@orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= format_text(order.order_status) %></td>
          <td><%= format_price(order.total) %></td>
          <td><%= order.updated_at %></td>
          <% if order.payment %>
            <td><%= link_to "View receipt", order.payment.receipt_url, class: "link-success" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

src/buysell2game/app/views/orders/show.html.erb
<h2>Order Summary</h2>
<section>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Item</th>
        <th scope="col">Price</th>
        <th scope="col">Remove?</th>
      </tr>
    </thead>
    <% if @order.items != nil %>
      <% total = 0 %>
      <% @items.each do |item| %>
        <tbody>
          <tr>
            <td><%= item.listing.listing_name %></td>
            <td><%= format_price(item.listing.price) %></td>
            <td><%= button_to "Remove item", { :controller => "items", :action => "destroy" }, { :method => :delete, :params => {:item_id => item.id},  class: "btn btn-sm btn-danger"} %></td>
          </tr>
        </tbody>
        <% total += item.listing.price %>
      <% end %>
    </table>
    <h3>Sub total: <%= format_price(total) %></h3>
    <%= button_to "Proceed to checkout", create_checkout_session_path,
      remote: true,
      method: :post,
      params: {id: @order.id},
      class: "btn btn-primary mb-3 pr-2",
      data: {disable_with: "Loading..."} %>
  <% else %>
    <%= link_to "Home", root_path %>
  <% end %>
</section>